[project]
name = "freecut-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "demucs>=4.0.1",
    "edge-tts>=7.2.8",
    "faster-whisper>=1.2.1",
    "google-genai>=2.2.0",
    "httpx>=0.28.1",
    "pyside6>=6.11.0",
    "pyside6-fluent-widgets>=1.11.2",
    "python-dotenv>=1.2.2",
    "qtawesome>=1.4.2",
    "sentencepiece>=0.2.1",
    "soundfile>=0.13.1",
    "torch>=2.11.0",
    "torchcodec>=0.11.1",
    "transformers>=5.8.0",
    "voxcpm>=2.0.3",
    "yt-dlp>=2026.3.17",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]
